import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildProgram } from "../src/cli-program.ts";
import { normalizeGeneratedSource } from "../src/completion/generated-source.ts";
import {
  commandSemantics,
  generateCommandContract,
  optionAuditPolicies,
} from "../src/contracts/cli-commands.ts";
import { renderAllCompletions } from "../src/completion/render.ts";
import { format } from "oxfmt";

const outputPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/generated/completions.ts",
);
const contract = generateCommandContract(
  buildProgram({ includeHelpBanner: false }),
  commandSemantics,
  optionAuditPolicies,
);
const unformatted = `// Generated by scripts/completions.ts. Do not edit.\nexport const GENERATED_COMPLETIONS = ${JSON.stringify(renderAllCompletions(contract), null, 2)} as const;\n`;
const { code: generated, errors } = await format(outputPath, unformatted, {
  printWidth: 100,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
});
if (errors.length > 0) {
  throw new Error(
    `Unable to format generated completions: ${errors.map((error) => error.message).join(", ")}`,
  );
}

if (process.argv.includes("--check")) {
  const current = existsSync(outputPath)
    ? normalizeGeneratedSource(readFileSync(outputPath, "utf8"))
    : "";
  if (current !== generated) {
    console.error("Generated shell completions are stale. Run `pnpm run completion:generate`.");
    process.exit(1);
  }
  console.log("Generated shell completions are current.");
} else {
  writeFileSync(outputPath, generated);
  console.log("Generated native shell completion artifacts.");
}
